
_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "./pretrained_weights/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RANK_ROI_HEAD:
    NAME: "RankRoiHead"
    
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
OUTPUT_DIR: "outputs/"
